examen_parcial/examen_parcial/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'gestion_tienda'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestion_tienda.urls'))
]

examen_parcial/gestion_tienda/urls.py
from django.urls import path
from . import views

app_name = 'gestion_tienda'

urlpatterns = [
    path('',views.index, name='index'),
    path ('cerrarSesion', views.cerrarSesion, name='cerrarSesion'),
    path('panelNavegacion', views.panelNavegacion, name='panelNavegacion'),
    path('eliminarUsuario/<str:ind>',views.eliminarUsuario,name='eliminarUsuario'),
    path ('datosProducto', views.datosProducto, name='datosProducto'),
    path ('eliminarProducto/<str:ind>',views.eliminarProducto,name='eliminarProducto'),
]

examen_parcial/gestion_tienda/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class datosUsuario(models.Model):
    nombreUsuario = models.CharField(max_length=30)
    apellidoUsuario = models.CharField(max_length=30)
    emailUsuario = models.EmailField(unique=True)
    user = models.OneToOneField (User, on_delete=models.CASCADE)
    contraUsuario = models.OneToOneField (User, on_delete=models.CASCADE)
    tipoUsuario = models.CharField(max_length=20, default='VENDEDOR')
    nroCelular = models.CharField(max_length=15)
    fechaIngreso = models.DateTimeField(default=date.today)

class datosProducto(models.Model):
    usuarioRelacionado = models.ForeignKey(User, on_delete=models.CASCADE)
    nombreProducto = models.CharField(max_length=100)
    codigoProducto = models.CharField(max_length=50)
    precioCompra = models.DecimalField(max_digits=10, decimal_places=2)
    precioVenta = models.DecimalField(max_digits=10, decimal_places=2)

examen_parcial/gestion_tienda/views.py
from collections import UserDict
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import datosUsuario
from .models import datosProducto

#Create your views here
def index(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        usuarioInfo = authenticate(request, username=nombreUsuario, password=contraUsuario)
        if usuarioInfo is not None:
            login(request,usuarioInfo)
            return HttpResponseRedirect (reverse('gestion_tienda:panelNavegacion'))
        else:
            return HttpResponseRedirect (reverse('gestion_tienda:index'))
    return render(request,'ingresoUsuario.html')

@login_required(login_url='http://127.0.0.1:8000')
def cerrarSesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('gestion_tienda:index'))

@login_required(login_url='http://127.0.0.1:8000')
def panelNavegacion(request):
    if request.user.datousuario.tipoUsuario == 'Administrador':
        if request.method == 'POST':
            nombreUsuario = request.POST.get('nombreUsuario')
            apellidoUsuario = request.POST.get('apellidoUsuario')
            emailUsuario = request.POST.get('emailUsuario')
            usernameUsuario = request.POST.get('usernameUsuario')
            contraUsuario = request.POST.get('contraUsuario')
            tipoUsuario = request.POST.get('tipoUsuario')
            nroCelular = request.POST.get('nroCelular')
            fechaIngreso = request.POST.get('fechaIngreso')

            usuarioNuevo = User.objects.create(
                username=usernameUsuario,
                email=emailUsuario,
            )

            usuarioNuevo.set_password(contraUsuario)
            usuarioNuevo.first_name = nombreUsuario
            usuarioNuevo.last_name = apellidoUsuario
            usuarioNuevo.is_staff = True
            usuarioNuevo.save()

            datosUsuario.objects.create(
                user=usuarioNuevo,
                tipoUsuario=tipoUsuario,
                nroCelular=nroCelular,
                fechaIngreso=fechaIngreso
            )
            return HttpResponseRedirect(reverse('gestion_tienda : panelNavegacion'))
        return render(request,'panelNavegacion.html',{
            'usuariosTotales':User.objects.all().order_by('id')
        })
    else:
        return HttpResponseRedirect(reverse('gestion_tienda : panelNavegacion'))

def eliminarUsuario(request,ind):
    usuarioEliminar = User.objects.get(id=ind)
    datosUsuario.objects.get(user=usuarioEliminar).delete()
    usuarioEliminar.delete()
    return HttpResponseRedirect(reverse('gestion_tienda:panelNavegacion'))

@login_required(login_url='http://127.0.0.1:8000')
def nuevoProducto (request):
    if request.method == 'POST':
        nombreProducto = request.POST.get('nombreProducto')
        codigoProducto = request.POST.get('codigoProducto')
        precioCompra = request.POST.get('precioCompra')
        precioVenta = request.POST.get('precioVenta')
        usernameUsuario = request.POST.get('usernameUsuario')

        productoNuevo = User.objects.create(
            nombreProducto = nombreProducto,
            codigoProducto = codigoProducto,
        )

        datosProducto.objects.create(
            precioCompra = precioCompra,
            precioVenta = precioVenta,
            username = usernameUsuario,
        )
        return HttpResponseRedirect(reverse('gestion_tienda : panelNavegacion'))
    return render(request,'panelNavegacion.html',{
        'productosTotales':User.objects.all().order_by('id')
    })

def eliminarProducto(request,ind):
        productoEliminar = User.objects.get(id=ind)
        datosProducto.objects.get(user=productoEliminar).delete()
        productoEliminar.delete()
        return HttpResponseRedirect(reverse('gestion_tienda:panelNavegacion'))

examen_parcial/gestion_tienda/templates/ingresoUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-info position-absolute start-50 top-50 translate-middle text-center" style="height: 900px; width: 1500px;">
            <div class="bg-body position-absolute start-50 top-50 translate-middle text-center rounded" style="width: 440px; height: 280px;">
                <form method="post" action="{% url 'gestion_tienda:index' %}">
                    <!--{% csrf_token %}-->
                    <h1 class="h1 mt-4 mb-3 ms-4 fw-bold text-start">Log in</h1>
                    <div class="form-group mb-3 ms-4 me-4">
                        <input class="form-control" type="text" name="nombreUsuario" placeholder="Username">
                    </div>
                    <div class="form-group mb-3 ms-4 me-4">
                        <input class="form-control" type="password" name="contraUsuario" placeholder="Password">
                    </div>
                    <div class="d-grid gap-2">
                        <button class="btn btn-info mb-3 ms-4 me-4 text-white" type="button">Log in</button>
                    </div>
                    <a class="h6 mb-3 text-decoration-none text-dark " href="#">or, sign up</a>
                </form>
            </div>
        </div>
    </body>
</html>

examen_parcial/gestion_tienda/templates/panelNavegacion.html
 <!--{% load static %}-->

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-info">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-4 mb-4 text-dark font-monospace">
                        <div class="row">
                            <h5>Bienvenida, {{user.first_name}} {{user.last_name}}</h5>
                        </div>
                        <div class="row">
                            <h8 class"fst-italic">{{ user.datosusuario.tipoUsuario}}</h8>
                        </div>
                    </div>  
                    <div class="col-1">
                         <a class="btn btn-light" href="{% url 'gestion_tienda:cerrarSesion' %}"><i class="fa-solid fa-right-to-bracket" style="color:#53d5fd"></i> Salir</a>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="mt-5 text-center font-bold">
            <h1>GESTION DE VENTAS</h1>
        </div>

        <div class="mt-5 container">
            <div class="row justify-content-between">
                <div class="col-3">
                    <button class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#nuevoUsuario"><i class="fa-solid fa-user-plus"></i> Gestion de usuario</button>
                </div>
                <div class="col-3">
                    <a class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#nuevoProducto"><i class="fa-solid fa-basket-shopping"></i> Gestion de producto</a>
                </div>
            </div>
        </div>

        <div class="mt-5 ms-5 me-5 container table-responsive-xxl">
            <div class="row justify-content">
                <div class="col-8 h8">
                    <table class="table">
                        <thead class="table-info">
                            <th>Producto</th>
                            <th>Codigo</th>
                            <th>Precio de compra</th>
                            <th>Precio de venta</th>
                            <th>Usuario</th>
                            <th>Eliminar</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ producto.nombreProducto }}</td>
                                <td>{{ usuario.codigoProducto }}</td>
                                <td>{{ usuario.datosusuario.precioCompra }}</td>
                                <td>{{ usuario.datosusuario.precioVenta }}</td>
                                <td>{{ usuario.datosusuario.usernameUsuario }}</td>
                                {% if user.datosusuario.tipoUsuario == 'Administrador'%}
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestion_tienda:eliminarProducto' usuario.id %}"><i class="fa-solid fa-trash"></i></a></td>
                                {% endif%}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nuevo usuario-->
{% if user.datosusuario.tipoUsuario == 'Administrador'%}
<div class="modal fade" id="nuevoUsuario" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'gestion_tienda:panelNavegacion' %}">
                <!--{% csrf_token %}-->
                <div class="modal-header">
                    <h5 class="modal-title">Crear nuevo usuario</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="row form-group justify-content-around mb-3">
                            <div class="col-5">
                                <label>Nombre :</label>
                                <input class="form-control" type="text" name="nombreUsuario" required>
                            </div>
                            <div class="col-5">
                                <label>Apellido :</label>
                                <input class="form-control" type="text" name="apellidoUsuario" required>
                            </div>
                        </div>
                        <div class="col-5">
                            <label>Username :</label>
                            <input class="form-control" type="text" name="usernameUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Password :</label>
                            <input class="form-control" type="password" name="contraUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Rol del usuario :</label>
                            <select class="form-select" name="tipoUsuario">
                                <option value="Vendedor">Vendedor</option>
                                <option value="ADMINISTRADOR">Administrador</option>
                            </select>
                        </div>
                        <div class="col-5">
                            <label>Nro de celular :</label>
                            <input class="form-control" type="text" name="nroCelular" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Email :</label>
                            <input class="form-control" type="email" name="emailUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Fecha de ingreso :</label>
                            <input class="form-control" type="date" name="fechaIngreso" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

<!--Nuevo Producto-->
<div class="modal fade" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'gestion_tienda:panelNavegacion' %}">
                <!--{% csrf_token %}-->
                <div class="modal-header">
                    <h5 class="modal-title">Crear nuevo producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="row form-group justify-content-around mb-3">
                            <div class="col-5">
                                <label>Nombre :</label>
                                <input class="form-control" type="text" name="nombreProducto" required>
                            </div>
                            <div class="col-5">
                                <label>Codigo :</label>
                                <input class="form-control" type="text" name="codigoProducto" required>
                            </div>
                        </div>
                        <div class="col-5">
                            <label>Precio de compra :</label>
                            <input class="form-control" type="money" name="precioCompra" required>
                        </div>
                        <div class="col-5">
                            <label>Precio de venta :</label>
                            <input class="form-control" type="text" name="precioVenta" required>
                        </div>
                        <div class="mt-3 col-5">
                            <label>Username :</label>
                            <input class="form-control" type="text" name="usernameUsuario" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>